var myName = prompt("silahkan ketik nama anda")
var birthdate = prompt("silahkan ketik tanggal lahir anda")
var adress = prompt("silahkan ketik alamat lengkap anda")
var education = prompt("silahkan ketik jenjang pendidikan terakhir anda")
alert('Data berhasil disimpan.\nTerima kasih atas partisipasi anda')
console.log(`name: ${myName}`)
console.log(`date of birth: ${birthdate}`)
console.log(`adress: ${adress}`)
console.log(`education: ${education}`)